{
  "openapi": "3.1.0",
  "info": {
    "title": "Pricing API",
    "description": "Servicio para la gestión de precios y tarifas de productos por fechas y prioridad.",
    "version": "1.0.0"
  },
  "servers": [
    {
      "url": "http://localhost:8080",
      "description": "Generated server url"
    }
  ],
  "tags": [
    {
      "name": "Prices",
      "description": "API para consulta de tarifas de precios de productos"
    }
  ],
  "paths": {
    "/api/prices": {
      "get": {
        "tags": [
          "Prices"
        ],
        "summary": "Consultar precio aplicable",
        "description": "Devuelve el precio con mayor prioridad para un producto, cadena y fecha específica.",
        "operationId": "getPrice",
        "parameters": [
          {
            "name": "filterPriceRequest",
            "in": "query",
            "description": "Objeto para filtrar los precios",
            "required": true,
            "schema": {
              "$ref": "#/components/schemas/FilterPriceRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Precio encontrado",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/PriceResponse"
                }
              }
            }
          },
          "404": {
            "description": "No se encontró un precio aplicable",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                },
                "example": {
                  "timestamp": "2020-06-14T16:00:00Z",
                  "status": 404,
                  "message": "No existe tarifa para la fecha indicada",
                  "path": "/api/prices"
                }
              }
            }
          },
          "400": {
            "description": "Parámetros de entrada inválidos",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                },
                "example": {
                  "timestamp": "2020-06-14T10:00:00Z",
                  "status": 400,
                  "message": "Parámetros de entrada inválidos",
                  "path": "/api/prices"
                }
              }
            }
          },
          "500": {
            "description": "Error Interno",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                },
                "example": {
                  "timestamp": "2020-06-14T16:00:00Z",
                  "status": 500,
                  "message": "Error Interno",
                  "path": "/api/prices"
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "FilterPriceRequest": {
        "type": "object",
        "properties": {
          "productId": {
            "type": "integer",
            "format": "int64",
            "description": "Identificador del producto",
            "example": 35455,
            "minimum": 1,
            "readOnly": true
          },
          "brandId": {
            "type": "integer",
            "format": "int32",
            "description": "Identificador de la marca",
            "example": 1,
            "minimum": 1,
            "readOnly": true
          },
          "dateToSearch": {
            "type": "string",
            "format": "date-time",
            "description": "Fecha de aplicación (ISO 8601)",
            "example": "2020-11-30T23:59:59",
            "readOnly": true
          }
        },
        "required": [
          "brandId",
          "dateToSearch",
          "productId"
        ]
      },
      "PriceResponse": {
        "type": "object",
        "description": "Información del precio final aplicable",
        "properties": {
          "productId": {
            "type": "integer",
            "format": "int64",
            "description": "Identificador del producto",
            "example": 1,
            "readOnly": true
          },
          "brandId": {
            "type": "integer",
            "format": "int32",
            "description": "Identificador de la marca",
            "example": 1,
            "readOnly": true
          },
          "priceList": {
            "type": "integer",
            "format": "int32",
            "description": "Tarifa de precios aplicable",
            "example": 3,
            "readOnly": true
          },
          "startDate": {
            "type": "string",
            "format": "date-time",
            "description": "Fecha de inicio del precio",
            "example": "2020-06-14-00.00.00",
            "readOnly": true
          },
          "endDate": {
            "type": "string",
            "format": "date-time",
            "description": "Fecha de fin del precio",
            "example": "2020-06-14-00.00.00",
            "readOnly": true
          },
          "finalPrice": {
            "type": "number",
            "description": "Precio entre las fechas marcadas",
            "example": 25.25,
            "readOnly": true
          },
          "currency": {
            "type": "string",
            "description": "Moneda",
            "example": "EUR",
            "readOnly": true
          }
        }
      },
      "ErrorResponse": {
        "type": "object",
        "description": "Objeto de error",
        "properties": {
          "timestamp": {
            "type": "string",
            "format": "date-time",
            "description": "Fecha del error",
            "example": "020-06-14-00.00.00",
            "readOnly": true
          },
          "status": {
            "type": "integer",
            "format": "int32",
            "description": "Código del error de la respuesta",
            "example": 404,
            "readOnly": true
          },
          "message": {
            "type": "string",
            "description": "Mensaje del error",
            "example": "Objeto no encontrado",
            "readOnly": true
          },
          "path": {
            "type": "string",
            "description": "LLamada que produjo el error",
            "example": "/list/prices",
            "readOnly": true
          }
        }
      }
    }
  }
}